#!/bin/sh

# 2. Write a script which delete an ACTIVE user on the VM.
# create a new active user -> then show list of active users -> then delete this user

useradd tykva & awk -F: '{print $1}' /etc/passwd & deluser --remove-home tykva
